<?php
namespace LavueCms;

use \Illuminate\Routing\Router;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

class LavueCmsRouteServiceProvider extends ServiceProvider
{
    protected $namespace = 'LavueCms\Http\Controller';

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function map(Router $router)
    {
        $router->middleware('web')
            ->namespace($this->namespace)
            ->group(__DIR__ . '/routes/web.php');
    }
}