<?php
namespace LavueCms;

use Illuminate\Routing\Router;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

class LavueCmsServiceProvider extends ServiceProvider
{
    /**
     * Indicates if loading of the provider is deferred.
     *
     * @var bool
     */
    protected $defer = false;

    /**
     * The controller namespace for the application.
     *
     * @var string|null
     */
    protected $namespace = 'LavueCms\Http\Controller';

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $this->loadMigrationsFrom(__DIR__.'/database/migrations');
        $this->loadViewsFrom(__DIR__.'/views', 'lavuecms');

        $this->publishes([
            __DIR__.'/resources/assets' => resource_path('assets/hobord/lavuecms'),
        ]);
    }

    public function map(Router $router)
    {
        $router->middleware('web')
            ->namespace($this->namespace)
            ->group(__DIR__ . '/routes/web.php');
    }
}